### ISSUE TITLE
recording issue 

### ISSUE THREAD

**Issue by satell** [introlab/odas_web#7]
I have installed odas library and odas web . My microphone array is respeaker v1 with raw frameware and after changing odas configuration file for odas web , it seems everything works fine but I don't have any WAV files and i receive this following error .  would you please help me to solve it ? 

![screenshot from 2018-04-24 12-01-35](https://user-images.githubusercontent.com/14195892/39180841-3d3f2a1a-47b8-11e8-9586-bc26f95ff0d3.png)
`root@user-LIFEBOOK-S752:/home/user/Desktop/odas/odas_web# npm start

> ODAS_Desktop@0.2.0 start /home/user/Desktop/odas/odas_web
> electron .

A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::9000
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Object.exports.startTrackingServer (/home/user/Desktop/odas/odas_web/servers.js:19:19)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/main.js:87:9)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/main.js:90:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::9001
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Object.exports.startPotentialServer (/home/user/Desktop/odas/odas_web/servers.js:97:20)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/main.js:88:9)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/main.js:90:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::10010
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at new AudioSocket (/home/user/Desktop/odas/odas_web/recordings.js:105:17)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/recordings.js:112:21)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/recordings.js:146:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::10000
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at new AudioSocket (/home/user/Desktop/odas/odas_web/recordings.js:105:17)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/recordings.js:112:21)
    at Object.<anonymous> (/home/user/Desktop/odas/odas_web/recordings.js:146:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
`

**Comment by tigaworx** [comment]
I had the same problem, but the solution provided by #8 solved it for me.
Edit line 114 of audio-recorder.js and change the filename to use `.toISOString()` rather than the locale string. Then the recorder won't try to save the wav in a subdirectory that does not exist.

**Comment by GodCed** [comment]
Solution is now merged in master.
