### ISSUE TITLE
npm success ,however npm start fail

### ISSUE THREAD

**Issue by tianrking** [introlab/odas_web#83]
> odas_studio@0.3.0 start /home/pi/Desktop/odas_web
> electron .

```env
(env) pi@raspberrypi:~/Desktop/odas_web $ node -v
v12.22.12
(env) pi@raspberrypi:~/Desktop/odas_web $ npm -v
6.14.16
```

error. Cant npm start
 
```bash
(process:26932): Gtk-WARNING **: 08:41:08.321: Locale not supported by C library.
	Using the fallback 'C' locale.

(electron:26932): Gtk-WARNING **: 08:41:08.322: cannot open display: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odas_studio@0.3.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the odas_studio@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-09-28T07_41_08_413Z-debug.log
```

error log

```node log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.16
3 info using node@v12.22.12
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle odas_studio@0.3.0~prestart: odas_studio@0.3.0
6 info lifecycle odas_studio@0.3.0~start: odas_studio@0.3.0
7 verbose lifecycle odas_studio@0.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle odas_studio@0.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Desktop/odas_web/node_modules/.bin:/home/pi/env/bin:/home/pi/download/openvino/deployment_tools/model_optimizer:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle odas_studio@0.3.0~start: CWD: /home/pi/Desktop/odas_web
10 silly lifecycle odas_studio@0.3.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle odas_studio@0.3.0~start: Returned: code: 1  signal: null
12 info lifecycle odas_studio@0.3.0~start: Failed to exec start script
13 verbose stack Error: odas_studio@0.3.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid odas_studio@0.3.0
15 verbose cwd /home/pi/Desktop/odas_web
16 verbose Linux 5.10.103-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.22.12
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error odas_studio@0.3.0 start: `electron .`
22 error Exit status 1
23 error Failed at the odas_studio@0.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by BroZL** [comment]
Hi, I encountered same issues. Did you solve it or you used alternative way

**Comment by JamesCHub** [comment]
Same problem.   After a few fixes, the npm install went fine, but npm start drew this error.


$ cat /home/pi/.npm/_logs/2022-11-24T21_50_19_165Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.16
3 info using node@v12.22.12
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle odas_studio@0.3.0~prestart: odas_studio@0.3.0
6 info lifecycle odas_studio@0.3.0~start: odas_studio@0.3.0
7 verbose lifecycle odas_studio@0.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle odas_studio@0.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/odas_web/node_modules/.bin:/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle odas_studio@0.3.0~start: CWD: /home/pi/odas_web
10 silly lifecycle odas_studio@0.3.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle odas_studio@0.3.0~start: Returned: code: 1  signal: null
12 info lifecycle odas_studio@0.3.0~start: Failed to exec start script
13 verbose stack Error: odas_studio@0.3.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid odas_studio@0.3.0
15 verbose cwd /home/pi/odas_web
16 verbose Linux 5.15.76-v8+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.22.12
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error odas_studio@0.3.0 start: `electron .`
22 error Exit status 1
23 error Failed at the odas_studio@0.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Running Debian Bullseye on pi4/8G

**Comment by BroZL** [comment]
Try a different version of pi is
